#!/usr/bin/env python3
"""Generate the test data header of the ntt_kyber app.

The accelerator computes the CRYSTALS-Kyber forward NTT exactly as the
reference ntt() of the pq-crystals repository does -- Cooley-Tukey butterflies
with Montgomery multiplication, len = 128..2, zetas[1..127] in order -- but
without the Barrett reduction that poly_ntt() applies afterwards. Both work in
int16 with the same truncations, so the hardware output must match ntt() bit
for bit, and that is what main.c checks.

The golden is computed here with an int16-exact model of that ntt(), and
main.c runs the same routine in C on the CPU and checks it against this golden
too, so a wrong model and a wrong accelerator cannot hide behind each other.

zetas[] is read from the .coe the accelerator's ROM is generated from
(hw/vendor/ntt_kyber/data/zetas_kyber.coe), so the C reference and the
hardware cannot use different tables.

Stimulus: uniformly random coefficients in (-q, q), seeded -- the input range
of ntt() in Kyber. Each stage grows a coefficient by at most q, so the outputs
stay below 8q = 26632 and never wrap int16.
"""

import argparse
import os
import random
import re

N = 256
Q = 3329
QINV = -3327  # q^-1 mod 2^16

COE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "../../../hw/vendor/ntt_kyber/data/zetas_kyber.coe")


def s16(x):
    """Wrap to int16, as a C assignment to int16_t does."""
    x &= 0xFFFF
    return x - 0x10000 if x & 0x8000 else x


def read_zetas(path):
    txt = open(path).read()
    vec = txt.split("memory_initialization_vector=")[1]
    words = [int(w, 16) for w in re.findall(r"[0-9A-Fa-f]+", vec)]
    assert len(words) == 128, f"{path}: expected 128 zetas, got {len(words)}"
    # 13-bit two's complement.
    return [w - (1 << 13) if w & (1 << 12) else w for w in words]


def montgomery_reduce(a):
    t = s16(s16(a) * QINV)
    return s16((a - t * Q) >> 16)


def ntt(r, zetas):
    r = list(r)
    k = 1
    length = 128
    while length >= 2:
        start = 0
        while start < N:
            zeta = zetas[k]
            k += 1
            for j in range(start, start + length):
                t = montgomery_reduce(zeta * r[j + length])
                r[j + length] = s16(r[j] - t)
                r[j] = s16(r[j] + t)
            start += 2 * length
        length >>= 1
    return r


def emit_array(ctype, name, values, size_expr, per_line=12, qualifier="static const"):
    print(f"{qualifier} {ctype} {name}[{size_expr}] = {{")
    for i in range(0, len(values), per_line):
        print("    " + ", ".join(f"{v:6d}" for v in values[i:i + per_line]) + ",")
    print("};\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--seed", type=int, default=1)
    args = ap.parse_args()

    zetas = read_zetas(COE)
    rng = random.Random(args.seed)
    poly = [rng.randint(-(Q - 1), Q - 1) for _ in range(N)]
    golden = ntt(poly, zetas)
    assert max(abs(v) for v in golden) < 8 * Q

    print("// Generated by gen_data.py; do not edit.")
    print("#ifndef DATASET_H")
    print("#define DATASET_H\n")
    print("#include <stdint.h>\n")
    print(f"#define NTT_N {N}")
    print(f"#define NTT_Q {Q}")
    print(f"#define NTT_QINV {QINV}\n")
    emit_array("int16_t", "zetas", zetas, "128")
    emit_array("int16_t", "ntt_in", poly, "NTT_N")
    emit_array("int16_t", "ntt_golden", golden, "NTT_N")
    print("#endif  // DATASET_H")


if __name__ == "__main__":
    main()
