// Generated by map2bitstream.py from gesummv_hv mapped on configs/4x4-HV.hjson
// Replayed from the committed regress/4x4-HV/gesummv_hv/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input0   ch 2   west of PE8        address=0x200 stride=4 size=3
//   in   input1   ch 4   west of PE4        address=0x210 stride=4 size=3
//   in   input3   ch 14  north of PE3       address=0x290 stride=4 size=3
//   in   input4   ch 19  router 1 hor_east  address=0x300 stride=4 size=3
//   in   input2   ch 22  east of PE15       address=0x280 stride=4 size=3
//   out  output1  ch 1   router 0 hor_west  address=0x404 size=1
//   out  output0  ch 10  south of PE13      address=0x400 size=1

#include <stdint.h>
#include "strela.h"

#define GESUMMV_HV_KERNEL_IN_INPUT0_CH 2
#define GESUMMV_HV_KERNEL_IN_INPUT1_CH 4
#define GESUMMV_HV_KERNEL_IN_INPUT3_CH 14
#define GESUMMV_HV_KERNEL_IN_INPUT4_CH 19
#define GESUMMV_HV_KERNEL_IN_INPUT2_CH 22
#define GESUMMV_HV_KERNEL_OUT_OUTPUT1_CH 1
#define GESUMMV_HV_KERNEL_OUT_OUTPUT0_CH 10

uint32_t gesummv_hv_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 12
    0x08000109, 0x003C0060, 0x00000402, 0x00000000, 0x00000000, // 8
    0x0800480A, 0x00BC010C, 0x00000802, 0x00000000, 0x00000000, // 4
    0x00200004, 0xC0240080, 0x00030400, 0x00000000, 0x00000000, // 0
    0x00003400, // routernode0

    0x00004203, 0x008C0300, 0x00000200, 0x00000000, 0x00000000, // 13
    0x08000008, 0xC0340400, 0x00030200, 0x00000000, 0x00000000, // 9
    0x00000000, 0x03CC1801, 0x00000102, 0x00000000, 0x00000002, // 5
    0x0800400A, 0x00BC0000, 0x00000040, 0x00000000, 0x00000000, // 1
    0x00029A00, // routernode1

    0x00008002, 0xC0142000, 0x00030100, 0x00000000, 0x00000000, // 14
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 10
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 6
    0x00008002, 0xC0142000, 0x00030100, 0x00000000, 0x00000000, // 2
    0x00000000, // routernode2

    0x20008002, 0x031C1800, 0x00000102, 0x00000000, 0x00000000, // 15
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 11
    0x00000000, 0x03CC0001, 0x00000082, 0x00000000, 0x00000003, // 7
    0x20000201, 0x030C1800, 0x00000102, 0x00000000, 0x00000000, // 3
    0x0000009A // routernode3
};
