// Generated by map2bitstream.py from bicg_hv mapped on configs/4x4-HV.hjson
// Replayed from the committed regress/4x4-HV/bicg_hv/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input4   ch 7   router 0 hor_west  address=0x300 stride=4 size=3
//   in   input3   ch 8   north of PE0       address=0x300 stride=4 size=3
//   in   input1   ch 10  north of PE1       address=0x20C stride=4 size=3
//   in   input2   ch 12  north of PE2       address=0x218 stride=4 size=3
//   in   input0   ch 14  north of PE3       address=0x200 stride=4 size=3
//   out  output3  ch 9   router 0 ver_ose   address=0x408 size=1
//   out  output1  ch 11  router 1 ver_ose   address=0x404 size=1
//   out  output2  ch 13  router 2 ver_ose   address=0x408 size=1
//   out  output0  ch 15  router 3 ver_ose   address=0x400 size=1

#include <stdint.h>
#include "strela.h"

#define MATVEC_S_KERNEL_IN_INPUT4_CH 7
#define MATVEC_S_KERNEL_IN_INPUT3_CH 8
#define MATVEC_S_KERNEL_IN_INPUT1_CH 10
#define MATVEC_S_KERNEL_IN_INPUT2_CH 12
#define MATVEC_S_KERNEL_IN_INPUT0_CH 14
#define MATVEC_S_KERNEL_OUT_OUTPUT3_CH 9
#define MATVEC_S_KERNEL_OUT_OUTPUT1_CH 11
#define MATVEC_S_KERNEL_OUT_OUTPUT2_CH 13
#define MATVEC_S_KERNEL_OUT_OUTPUT0_CH 15

uint32_t matvec_s_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 12
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 8
    0x00000201, 0xC0044000, 0x00030080, 0x00000000, 0x00000000, // 4
    0x00000201, 0x038C0301, 0x00000202, 0x00000000, 0x00000000, // 0
    0x0003D10A, // routernode0

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 13
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 9
    0x00000201, 0xC0044000, 0x00030080, 0x00000000, 0x00000000, // 5
    0x00000201, 0x038C0301, 0x00000202, 0x00000000, 0x00000000, // 1
    0x0000010A, // routernode1

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 14
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 10
    0x00000201, 0xC0044000, 0x00030080, 0x00000000, 0x00000000, // 6
    0x00000201, 0x038C0301, 0x00000202, 0x00000000, 0x00000000, // 2
    0x0000010A, // routernode2

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 15
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 11
    0x00000201, 0xC0044000, 0x00030080, 0x00000000, 0x00000000, // 7
    0x00000201, 0x038C0301, 0x00000202, 0x00000000, 0x00000000, // 3
    0x0000010A // routernode3
};
