#!/usr/bin/env python3
"""Generate the test data header of the {{ip}} app.

TODO: what the accelerator computes, the exact arithmetic it uses (widths,
wrapping, rounding), and why the model below reproduces it bit for bit.

The golden is computed here with an independent Python model; main.c runs the
same computation in C on the CPU and checks it against this golden too, so a
wrong model and a wrong accelerator cannot hide behind each other.

Writes dataset.h to stdout (make app runs it through gen-app-data). Seeded, so
the header is reproducible.
"""

import argparse
import random

N = 256  # TODO default size: small enough for Verilator (~2 kcycles/s)


def s32(x):
    """Wrap to int32, as a C assignment to int32_t does."""
    x &= 0xFFFFFFFF
    return x - 0x100000000 if x & 0x80000000 else x


def model(data):
    """TODO: the reference computation, mirroring the hardware arithmetic."""
    return [s32(v) for v in data]


def emit_array(ctype, name, values, size_expr, per_line=8):
    print(f"static const {ctype} {name}[{size_expr}] = {{")
    for i in range(0, len(values), per_line):
        print("    " + ", ".join(f"{v:11d}" for v in values[i : i + per_line]) + ",")
    print("};\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--n", type=int, default=N)
    args = ap.parse_args()

    rng = random.Random(args.seed)
    data = [rng.randint(-1000, 1000) for _ in range(args.n)]  # TODO input range
    golden = model(data)

    print("// Generated by gen_data.py; do not edit.")
    print("#ifndef DATASET_H")
    print("#define DATASET_H\n")
    print("#include <stdint.h>\n")
    print(f"#define DATA_N {args.n}")
    print("typedef int32_t DATA_T;\n")
    emit_array("DATA_T", "data_in", data, "DATA_N")
    emit_array("DATA_T", "golden", golden, "DATA_N")
    print("#endif  // DATASET_H")


if __name__ == "__main__":
    main()
