// Generated by map2bitstream.py from fir mapped on configs/4x4.hjson
// Replayed from the committed regress/4x4/fir/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input0   ch 1  north of PE1   address=0x200 stride=4 size=100
//   out  output0  ch 1  south of PE13  address=0x400 size=100

#include <stdint.h>
#include "strela.h"

#define FIR_KERNEL_IN_INPUT0_CH 1
#define FIR_KERNEL_OUT_OUTPUT0_CH 1

uint32_t fir_kernel[STRELA_V1_CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 12
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 8
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 4
    0x00008002, 0x021C0060, 0x00000102, 0x00000000, 0x00000060, // 0

    0x00000201, 0x020C0300, 0x00000084, 0x00000000, 0xFFFFFFF8, // 13
    0x00004203, 0x008C0300, 0x00000080, 0x00000000, 0x00000000, // 9
    0x00004203, 0x008C0300, 0x00004080, 0x00000000, 0x00000000, // 5
    0x0800405B, 0x00BC0300, 0x00004080, 0x00000000, 0x00000000, // 1

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 14
    0x00000201, 0x020C1800, 0x00000042, 0x00000000, 0x00000020, // 10
    0x00000221, 0x020C1800, 0x00000042, 0x00000000, 0x00000060, // 6
    0x08400008, 0x023C1A00, 0x00004042, 0x00000000, 0x00000020, // 2

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 15
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 11
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 7
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000 // 3
};
