// Generated by map2bitstream.py from fir8 mapped on configs/4x4-HV.hjson
// Replayed from the committed regress/4x4-HV/fir8/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input0   ch 10  north of PE1   address=0x200 stride=4 size=100
//   out  output0  ch 8   south of PE12  address=0x400 size=100

#include <stdint.h>
#include "strela.h"

#define FIR8_KERNEL_IN_INPUT0_CH 10
#define FIR8_KERNEL_OUT_OUTPUT0_CH 8

uint32_t fir8_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00000201, 0x020C0300, 0x00000204, 0x00000000, 0xFFFFFFF8, // 12
    0x00004203, 0x008C0300, 0x00000200, 0x00000000, 0x00000000, // 8
    0x00004203, 0x008C0300, 0x00004200, 0x00000000, 0x00000000, // 4
    0x80004002, 0x00FC0300, 0x00004200, 0x00000000, 0x00000000, // 0
    0x00005800, // routernode0

    0x00000201, 0x020C0060, 0x00000402, 0x00000000, 0x0000000E, // 13
    0x00000261, 0x020C1800, 0x00000102, 0x00000000, 0x00000002, // 9
    0x00000261, 0x020C1800, 0x00000102, 0x00000000, 0xFFFFFFF2, // 5
    0x00000261, 0x020C1800, 0x00000102, 0x00000000, 0x0000002A, // 1
    0x00000000, // routernode1

    0x08000109, 0x003C0060, 0x00004400, 0x00000000, 0x00000000, // 14
    0x08800008, 0x023C0340, 0x00004202, 0x00000000, 0xFFFFFFFE, // 10
    0x08000008, 0x023C0060, 0x00000402, 0x00000000, 0x00000046, // 6
    0x08000008, 0x023C0060, 0x00000402, 0x00000000, 0xFFFFFFBA, // 2
    0x00000000, // routernode2

    0x08000109, 0x003C000C, 0x00004800, 0x00000000, 0x00000000, // 15
    0x0804000C, 0x023C0304, 0x00000202, 0x00000000, 0xFFFFFFD6, // 11
    0x0420000C, 0x01AC000C, 0x00004800, 0x00000000, 0x00000000, // 7
    0x0420000C, 0x01AC0000, 0x00004040, 0x00000000, 0x00000000, // 3
    0x00000000 // routernode3
};
