// Generated by map2bitstream.py from fft_full mapped on configs/4x4-HV.hjson
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input3   ch 5   router 1 hor_west  address=0x320 stride=4 size=8
//   in   input5   ch 9   router 0 ver_ise   address=0x260 stride=4 size=8
//   in   input1   ch 11  router 1 ver_ise   address=0x220 stride=4 size=8
//   in   input4   ch 13  router 2 ver_ise   address=0x240 stride=4 size=8
//   in   input0   ch 15  router 3 ver_ise   address=0x200 stride=4 size=8
//   in   input2   ch 23  router 3 hor_east  address=0x300 stride=4 size=8
//   out  output2  ch 8   south of PE12      address=0x440 size=8
//   out  output3  ch 10  south of PE13      address=0x460 size=8
//   out  output0  ch 12  south of PE14      address=0x400 size=8
//   out  output1  ch 14  south of PE15      address=0x420 size=8

#include <stdint.h>
#include "strela.h"

#define FFT_FULL_KERNEL_IN_INPUT3_CH 5
#define FFT_FULL_KERNEL_IN_INPUT5_CH 9
#define FFT_FULL_KERNEL_IN_INPUT1_CH 11
#define FFT_FULL_KERNEL_IN_INPUT4_CH 13
#define FFT_FULL_KERNEL_IN_INPUT0_CH 15
#define FFT_FULL_KERNEL_IN_INPUT2_CH 23
#define FFT_FULL_KERNEL_OUT_OUTPUT2_CH 8
#define FFT_FULL_KERNEL_OUT_OUTPUT3_CH 10
#define FFT_FULL_KERNEL_OUT_OUTPUT0_CH 12
#define FFT_FULL_KERNEL_OUT_OUTPUT1_CH 14

uint32_t fft_full_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x20000201, 0x030C0300, 0x00000200, 0x00000000, 0x00000000, // 12
    0x10004802, 0x00EC0160, 0x00000401, 0x00000000, 0x00000000, // 8
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 4
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 0
    0x000000C8, // routernode0

    0x10001023, 0x03EC0061, 0x00000402, 0x00000000, 0x00000000, // 13
    0x0050020D, 0x010C1A00, 0x00000100, 0x00000000, 0x00000000, // 9
    0x10000000, 0x03EC0301, 0x00000202, 0x00000000, 0x00000000, // 5
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 1
    0x000190A8, // routernode1

    0xA1000029, 0x037C1808, 0x00000102, 0x00000000, 0x00000000, // 14
    0x00200907, 0x002C0160, 0x00000401, 0x00000000, 0x00000000, // 10
    0xA0000000, 0x037C0300, 0x00000202, 0x00000000, 0x00000000, // 6
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 2
    0x000000A8, // routernode2

    0x10000101, 0x006C0300, 0x00000201, 0x00000000, 0x00000000, // 15
    0x14400008, 0x01EC1A00, 0x00000100, 0x00000000, 0x00000000, // 11
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 7
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 3
    0x00019AC8 // routernode3
};
