// Generated by map2bitstream.py from gemm_2 mapped on configs/4x4.hjson
// Replayed from the committed regress/4x4/gemm_2/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input3   ch 0  north of PE0   address=0x500 stride=4 size=100
//   in   input2   ch 1  north of PE1   address=0x400 stride=4 size=100
//   in   input0   ch 2  north of PE2   address=0x200 stride=4 size=100
//   in   input1   ch 3  north of PE3   address=0x300 stride=4 size=100
//   out  output1  ch 0  south of PE12  address=0x700 size=100
//   out  output0  ch 3  south of PE15  address=0x600 size=100

#include <stdint.h>
#include "strela.h"

#define GEMM_2_KERNEL_IN_INPUT3_CH 0
#define GEMM_2_KERNEL_IN_INPUT2_CH 1
#define GEMM_2_KERNEL_IN_INPUT0_CH 2
#define GEMM_2_KERNEL_IN_INPUT1_CH 3
#define GEMM_2_KERNEL_OUT_OUTPUT1_CH 0
#define GEMM_2_KERNEL_OUT_OUTPUT0_CH 3

uint32_t gemm_2_kernel[STRELA_V1_CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00000021, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 12
    0x00000021, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 8
    0x00008103, 0x001C0300, 0x00000080, 0x00000000, 0x00000000, // 4
    0x00000101, 0x004C0300, 0x00000082, 0x00000000, 0x00000003, // 0

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 13
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 9
    0x00000011, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 5
    0x00000101, 0x004C0300, 0x00000082, 0x00000000, 0x0000000F, // 1

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 14
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 10
    0x00000041, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 6
    0x00000101, 0x004C0300, 0x00000082, 0x00000000, 0x0000000F, // 2

    0x00000021, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 15
    0x00000021, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 11
    0x08000109, 0x003C0300, 0x00000080, 0x00000000, 0x00000000, // 7
    0x00000101, 0x004C0300, 0x00000082, 0x00000000, 0x00000003 // 3
};
