// Generated by map2bitstream.py from mm mapped on configs/4x4.hjson
// Replayed from the committed regress/4x4/mm/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input3   ch 0  north of PE0   address=0x300 stride=4 size=3
//   in   input1   ch 1  north of PE1   address=0x20C stride=4 size=3
//   in   input2   ch 2  north of PE2   address=0x218 stride=4 size=3
//   in   input0   ch 3  north of PE3   address=0x200 stride=4 size=3
//   out  output1  ch 1  south of PE13  address=0x404 size=1
//   out  output2  ch 2  south of PE14  address=0x408 size=1
//   out  output0  ch 3  south of PE15  address=0x400 size=1

#include <stdint.h>
#include "strela.h"

#define MM_KERNEL_IN_INPUT3_CH 0
#define MM_KERNEL_IN_INPUT1_CH 1
#define MM_KERNEL_IN_INPUT2_CH 2
#define MM_KERNEL_IN_INPUT0_CH 3
#define MM_KERNEL_OUT_OUTPUT1_CH 1
#define MM_KERNEL_OUT_OUTPUT2_CH 2
#define MM_KERNEL_OUT_OUTPUT0_CH 3

uint32_t mm_kernel[STRELA_V1_CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 12
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 8
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 4
    0x00000041, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 0

    0x00000021, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 13
    0x00000021, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 9
    0x00000201, 0xC0040400, 0x00030080, 0x00000000, 0x00000000, // 5
    0x04800209, 0x018C0340, 0x00000082, 0x00000000, 0x00000000, // 1

    0x00000021, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 14
    0x00000021, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 10
    0x00000201, 0xC0040400, 0x00030080, 0x00000000, 0x00000000, // 6
    0x04800209, 0x018C0340, 0x00000082, 0x00000000, 0x00000000, // 2

    0x00000021, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 15
    0x00000021, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 11
    0x00000201, 0xC0040400, 0x00030080, 0x00000000, 0x00000000, // 7
    0x04000209, 0x018C0300, 0x00000082, 0x00000000, 0x00000000 // 3
};
