// Generated by map2bitstream.py from gemm_2_hv mapped on configs/4x4-HV.hjson
// Replayed from the committed regress/4x4-HV/gemm_2_hv/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input2   ch 8   north of PE0      address=0x400 stride=4 size=100
//   in   input1   ch 10  north of PE1      address=0x300 stride=4 size=100
//   in   input3   ch 12  north of PE2      address=0x500 stride=4 size=100
//   in   input0   ch 14  north of PE3      address=0x200 stride=4 size=100
//   out  output1  ch 11  router 1 ver_ose  address=0x700 size=100
//   out  output0  ch 15  router 3 ver_ose  address=0x600 size=100

#include <stdint.h>
#include "strela.h"

#define GEMM_2_HV_KERNEL_IN_INPUT2_CH 8
#define GEMM_2_HV_KERNEL_IN_INPUT1_CH 10
#define GEMM_2_HV_KERNEL_IN_INPUT3_CH 12
#define GEMM_2_HV_KERNEL_IN_INPUT0_CH 14
#define GEMM_2_HV_KERNEL_OUT_OUTPUT1_CH 11
#define GEMM_2_HV_KERNEL_OUT_OUTPUT0_CH 15

uint32_t gemm_2_hv_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 12
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 8
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 4
    0x00000101, 0x004C0060, 0x00000402, 0x00000000, 0x00000003, // 0
    0x00000000, // routernode0

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 13
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 9
    0x00000101, 0x004C0060, 0x00000402, 0x00000000, 0x00000003, // 5
    0x0800402B, 0x00BC0000, 0x00000080, 0x00000000, 0x00000000, // 1
    0x00000109, // routernode1

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 14
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 10
    0x00800008, 0x00000040, 0x00000000, 0x00000000, 0x00000000, // 6
    0x00000101, 0x004C1800, 0x00000102, 0x00000000, 0x00000003, // 2
    0x00000000, // routernode2

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 15
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 11
    0x04000209, 0x018C0000, 0x00000080, 0x00000000, 0x00000000, // 7
    0x00000101, 0x004C0300, 0x00000202, 0x00000000, 0x00000003, // 3
    0x0000010A // routernode3
};
