// Generated by map2bitstream.py from 2mm_1_hv mapped on configs/4x4-HV.hjson
// Replayed from the committed regress/4x4-HV/2mm_1_hv/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input1   ch 9   router 0 ver_ise   address=0x20C stride=4 size=3
//   in   input0   ch 11  router 1 ver_ise   address=0x200 stride=4 size=3
//   in   input3   ch 13  router 2 ver_ise   address=0x218 stride=4 size=3
//   in   input2   ch 15  router 3 ver_ise   address=0x218 stride=4 size=3
//   in   input5   ch 17  router 0 hor_east  address=0x300 stride=4 size=3
//   in   input4   ch 21  router 2 hor_east  address=0x300 stride=4 size=3
//   out  output5  ch 0   west of PE0        address=0x400 size=1
//   out  output7  ch 3   router 1 hor_west  address=0x400 size=1
//   out  output4  ch 4   west of PE8        address=0x400 size=1
//   out  output1  ch 8   south of PE12      address=0x400 size=1
//   out  output0  ch 10  south of PE13      address=0x400 size=1
//   out  output3  ch 12  south of PE14      address=0x400 size=1
//   out  output2  ch 16  east of PE15       address=0x400 size=1
//   out  output6  ch 20  east of PE7        address=0x400 size=1

#include <stdint.h>
#include "strela.h"

#define MM_ABC_KERNEL_IN_INPUT1_CH 9
#define MM_ABC_KERNEL_IN_INPUT0_CH 11
#define MM_ABC_KERNEL_IN_INPUT3_CH 13
#define MM_ABC_KERNEL_IN_INPUT2_CH 15
#define MM_ABC_KERNEL_IN_INPUT5_CH 17
#define MM_ABC_KERNEL_IN_INPUT4_CH 21
#define MM_ABC_KERNEL_OUT_OUTPUT5_CH 0
#define MM_ABC_KERNEL_OUT_OUTPUT7_CH 3
#define MM_ABC_KERNEL_OUT_OUTPUT4_CH 4
#define MM_ABC_KERNEL_OUT_OUTPUT1_CH 8
#define MM_ABC_KERNEL_OUT_OUTPUT0_CH 10
#define MM_ABC_KERNEL_OUT_OUTPUT3_CH 12
#define MM_ABC_KERNEL_OUT_OUTPUT2_CH 16
#define MM_ABC_KERNEL_OUT_OUTPUT6_CH 20

uint32_t mm_abc_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00000201, 0xC0040400, 0x00030200, 0x00000000, 0x00000000, // 12
    0x10000402, 0x03EC0B01, 0x00000202, 0x00000000, 0x00000000, // 8
    0x00000201, 0xC0040010, 0x00030800, 0x00000000, 0x00000000, // 4
    0x10010004, 0x03EC1301, 0x00000202, 0x00000000, 0x00000000, // 0
    0x0003DA58, // routernode0

    0x00000201, 0xC0040400, 0x00030200, 0x00000000, 0x00000000, // 13
    0x10000011, 0x03EC0301, 0x00000202, 0x00000000, 0x00000000, // 9
    0x00000201, 0xC0040400, 0x00030200, 0x00000000, 0x00000000, // 5
    0x10000000, 0x03EC0301, 0x00000202, 0x00000000, 0x00000000, // 1
    0x00003658, // routernode1

    0x00000201, 0xC0040400, 0x00030200, 0x00000000, 0x00000000, // 14
    0x10000000, 0x03EC0301, 0x00000202, 0x00000000, 0x00000000, // 10
    0x00000201, 0xC0050000, 0x00030040, 0x00000000, 0x00000000, // 6
    0x10000000, 0x03EC0301, 0x00000202, 0x00000000, 0x00000000, // 2
    0x0003DA58, // routernode2

    0x00000201, 0xC0040080, 0x00030400, 0x00000000, 0x00000000, // 15
    0x10000000, 0x03EC0301, 0x00000202, 0x00000000, 0x00000000, // 11
    0x00000201, 0xC0040080, 0x00030400, 0x00000000, 0x00000000, // 7
    0x10000000, 0x03EC0301, 0x00000202, 0x00000000, 0x00000000, // 3
    0x00000058 // routernode3
};
