// Generated by map2bitstream.py from gemver_3_hv mapped on configs/4x4-HV.hjson
// Replayed from the committed regress/4x4-HV/gemver_3_hv/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input1   ch 8   north of PE0      address=0x300 stride=4 size=100
//   in   input0   ch 10  north of PE1      address=0x200 stride=4 size=100
//   in   input2   ch 12  north of PE2      address=0x400 stride=4 size=100
//   in   input3   ch 14  north of PE3      address=0x500 stride=4 size=100
//   out  output0  ch 9   router 0 ver_ose  address=0x600 size=100
//   out  output1  ch 15  router 3 ver_ose  address=0x700 size=100

#include <stdint.h>
#include "strela.h"

#define ADD_KERNEL_IN_INPUT1_CH 8
#define ADD_KERNEL_IN_INPUT0_CH 10
#define ADD_KERNEL_IN_INPUT2_CH 12
#define ADD_KERNEL_IN_INPUT3_CH 14
#define ADD_KERNEL_OUT_OUTPUT0_CH 9
#define ADD_KERNEL_OUT_OUTPUT1_CH 15

uint32_t add_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 12
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 8
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 4
    0x00008103, 0x001C0000, 0x00000080, 0x00000000, 0x00000000, // 0
    0x00000109, // routernode0

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 13
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 9
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 5
    0x00000011, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 1
    0x00000000, // routernode1

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 14
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 10
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 6
    0x00000041, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 2
    0x00000000, // routernode2

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 15
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 11
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 7
    0x08000109, 0x003C0000, 0x00000080, 0x00000000, 0x00000000, // 3
    0x00000109 // routernode3
};
