// Generated by map2bitstream.py from gemver_1_hv mapped on configs/4x4-HV.hjson
// Replayed from the committed regress/4x4-HV/gemver_1_hv/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input4   ch 2   west of PE8        address=0x400 stride=4 size=100
//   in   input2   ch 6   west of PE0        address=0x400 stride=4 size=100
//   in   input0   ch 10  north of PE1       address=0x200 stride=4 size=100
//   in   input1   ch 12  north of PE2       address=0x300 stride=4 size=100
//   in   input6   ch 17  router 0 hor_east  address=0x400 stride=4 size=100
//   in   input3   ch 18  east of PE7        address=0x500 stride=4 size=100
//   in   input7   ch 21  router 2 hor_east  address=0x500 stride=4 size=100
//   in   input5   ch 22  east of PE15       address=0x500 stride=4 size=100
//   out  output0  ch 11  router 1 ver_ose   address=0x600 size=100
//   out  output1  ch 13  router 2 ver_ose   address=0x700 size=100

#include <stdint.h>
#include "strela.h"

#define UPDATE_KERNEL_IN_INPUT4_CH 2
#define UPDATE_KERNEL_IN_INPUT2_CH 6
#define UPDATE_KERNEL_IN_INPUT0_CH 10
#define UPDATE_KERNEL_IN_INPUT1_CH 12
#define UPDATE_KERNEL_IN_INPUT6_CH 17
#define UPDATE_KERNEL_IN_INPUT3_CH 18
#define UPDATE_KERNEL_IN_INPUT7_CH 21
#define UPDATE_KERNEL_IN_INPUT5_CH 22
#define UPDATE_KERNEL_OUT_OUTPUT0_CH 11
#define UPDATE_KERNEL_OUT_OUTPUT1_CH 13

uint32_t update_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 12
    0x08000008, 0x03BC000D, 0x00000802, 0x00000000, 0x00000000, // 8
    0x00100205, 0x010C0060, 0x00000400, 0x00000000, 0x00000000, // 4
    0x08000008, 0x03BC0301, 0x00000202, 0x00000000, 0x00000000, // 0
    0x00025A00, // routernode0

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 13
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 9
    0x01000008, 0x00000008, 0x00000000, 0x00000000, 0x00000000, // 5
    0x00200105, 0x002C0000, 0x00000080, 0x00000000, 0x00000000, // 1
    0x00000109, // routernode1

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 14
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 10
    0x00001002, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 6
    0x00200105, 0x002C0000, 0x00000080, 0x00000000, 0x00000000, // 2
    0x00025B09, // routernode2

    0x00001002, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 15
    0x00200004, 0x03AC000D, 0x00000802, 0x00000000, 0x00000000, // 11
    0x00101207, 0x010C1800, 0x00000100, 0x00000000, 0x00000000, // 7
    0x00200004, 0x03AC0301, 0x00000202, 0x00000000, 0x00000000, // 3
    0x00000000 // routernode3
};
