// Generated by map2bitstream.py from fft_st mapped on configs/4x4-HV.hjson
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input0   ch 9   router 0 ver_ise  address=0x200 stride=4 size=8
//   in   input2   ch 11  router 1 ver_ise  address=0x240 stride=4 size=8
//   in   input1   ch 13  router 2 ver_ise  address=0x220 stride=4 size=8
//   in   input3   ch 15  router 3 ver_ise  address=0x260 stride=4 size=8
//   out  output0  ch 8   south of PE12     address=0x400 size=8
//   out  output1  ch 10  south of PE13     address=0x420 size=8
//   out  output3  ch 12  south of PE14     address=0x460 size=8
//   out  output2  ch 14  south of PE15     address=0x440 size=8

#include <stdint.h>
#include "strela.h"

#define FFT_ST_KERNEL_IN_INPUT0_CH 9
#define FFT_ST_KERNEL_IN_INPUT2_CH 11
#define FFT_ST_KERNEL_IN_INPUT1_CH 13
#define FFT_ST_KERNEL_IN_INPUT3_CH 15
#define FFT_ST_KERNEL_OUT_OUTPUT0_CH 8
#define FFT_ST_KERNEL_OUT_OUTPUT1_CH 10
#define FFT_ST_KERNEL_OUT_OUTPUT3_CH 12
#define FFT_ST_KERNEL_OUT_OUTPUT2_CH 14

uint32_t fft_st_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x10000101, 0x006C0300, 0x00000200, 0x00000000, 0x00000000, // 12
    0x10000121, 0x006C0060, 0x00000401, 0x00000000, 0x00000000, // 8
    0x00000802, 0x00000100, 0x00000000, 0x00000000, 0x00000000, // 4
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 0
    0x000000C8, // routernode0

    0x00000021, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 13
    0x10400008, 0x026C0260, 0x00000402, 0x00000000, 0x00000005, // 9
    0x00008103, 0x001C1800, 0x00000101, 0x00000000, 0x00000000, // 5
    0x10000000, 0x026C0300, 0x00000202, 0x00000000, 0x00000003, // 1
    0x00000058, // routernode1

    0x10000021, 0x026C000C, 0x00000802, 0x00000000, 0x00000003, // 14
    0x0420080E, 0x01AC0160, 0x00000400, 0x00000000, 0x00000000, // 10
    0x10000000, 0x026C1800, 0x00000102, 0x00000000, 0x00000005, // 6
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 2
    0x000000A8, // routernode2

    0x20000201, 0x030C0300, 0x00000200, 0x00000000, 0x00000000, // 15
    0x14400008, 0x01EC1A00, 0x00000101, 0x00000000, 0x00000000, // 11
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 7
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 3
    0x000000C8 // routernode3
};
