#!/usr/bin/env python3
# Copyright 2026 EPFL, Politecnico di Torino, and Universidad Politecnica de Madrid.
# Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#
# Author: Daniel Vázquez
# Description: Emit a STRELA <app>_kernel.h from a committed regress bitstream.

"""Rebuild an app's C kernel header from a *committed* elastic-cgra bitstream.

`rtl/elastic-cgra/regress/<fabric>/<app>/` holds a committed `bitstream.bin` and
`io_map.json` for 21 HV kernels. The io_map already carries the `location`
fields `strela_bind` needs, and `CGRA.load_bin()` replays the bitstream into the
same in-memory model `CGRA.write_c_header()` emits from -- so the kernel header
can be regenerated without Gurobi and without the ~10 minute mapper solve.

Verified against a live `fir8_hv` solve: the header and io_map produced here are
byte-identical to the mapper's, and the model round-trips back to the committed
`.bin` exactly (this script checks that round-trip on every run and fails if it
ever stops holding).

Use the mapper (`make -C rtl/elastic-cgra map-bitstream`) only for a DFG with no
committed bitstream, or after changing a DFG.

    scripts/gr_heep_env.sh python3 scripts/regress2kernel.py gesummv_hv \\
        -o sw/applications/strela_gesummv/gesummv_hv_kernel.h
"""

import argparse
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_CGRA = os.path.abspath(os.path.join(
    _HERE, "..", "hw", "vendor", "ceimm_upm_strela", "rtl", "elastic-cgra"))


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("app", help="regress application name, e.g. gesummv_hv")
    ap.add_argument("--cgra-root", default=_CGRA,
                    help="elastic-cgra checkout (default: the vendored one)")
    ap.add_argument("--fabric", default="4x4-HV",
                    help="fabric config name (default: 4x4-HV, the only one "
                         "the STRELA shell accepts)")
    ap.add_argument("--array-name",
                    help="C array name (default: <app>_kernel)")
    ap.add_argument("-o", "--output", required=True,
                    help="path of the .h to write")
    args = ap.parse_args()

    root = os.path.abspath(args.cgra_root)
    sys.path.insert(0, os.path.join(root, "bitstream"))
    import hjson
    from CGRA import CGRA, c_identifier, vertical_bus_ends

    cfg_path = os.path.join(root, "configs", f"{args.fabric}.hjson")
    with open(cfg_path, encoding="utf-8") as fh:
        cfg = hjson.load(fh)

    rows = int(cfg["dimensions"]["rows"])
    cols = int(cfg["dimensions"]["cols"])
    has_hv = bool(cfg.get("has_hvroutes", False))
    # These widen the router configuration word, so they must match the config
    # the committed bitstream was written from or load_bin misparses it.
    ver_south_in, ver_north_out = vertical_bus_ends(
        cfg.get("inputs"), cfg.get("outputs"))

    regress = os.path.join(root, "regress", args.fabric, args.app)
    bin_path = os.path.join(regress, "bitstream.bin")
    iomap_path = os.path.join(regress, "io_map.json")
    for path in (bin_path, iomap_path):
        if not os.path.isfile(path):
            raise SystemExit(
                f"{path} not found. Only kernels with a committed regress "
                f"bitstream can use this fast path; run the mapper instead:\n"
                f"  make -C {os.path.relpath(root)} map-bitstream "
                f"PROJECT={args.app} CGRA_CONFIG=configs/{args.fabric}.hjson")

    cgra = CGRA(rows, cols, has_hvroutes=has_hv,
                ver_south_in=ver_south_in, ver_north_out=ver_north_out)
    cgra.load_bin(bin_path)

    with open(iomap_path, encoding="utf-8") as fh:
        io_map = json.load(fh)

    array_name = c_identifier(args.array_name or f"{args.app}_kernel")
    # The first line must match strela_lint.py's PROVENANCE regex -- that is how
    # `make lint-kernel` finds the DFG to check the bitstream against. It is the
    # honest provenance of the *bitstream*; the second line records how this
    # header was produced from it.
    source = (f"Generated by map2bitstream.py from {args.app} mapped on "
              f"configs/{args.fabric}.hjson\n"
              f"// Replayed from the committed regress/{args.fabric}/{args.app}/"
              f"bitstream.bin by regress2kernel.py (no mapper run)")

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    cgra.write_c_header(array_name, args.output, io_map=io_map, source=source)

    # Round-trip: if the model did not decode the bitstream faithfully, the
    # header would be wrong in ways only a deadlock would reveal.
    tmp = args.output + ".roundtrip.bin"
    cgra.write_bin(tmp)
    with open(bin_path, "rb") as a, open(tmp, "rb") as b:
        orig, again = a.read(), b.read()
    os.remove(tmp)
    if orig != again:
        os.remove(args.output)
        raise SystemExit(
            f"round-trip check FAILED: re-emitting the loaded bitstream gave "
            f"{len(again)} bytes that differ from the committed {len(orig)}. "
            f"The CGRA model and this bitstream disagree; use the mapper.")

    print(f"fabric    : {rows}x{cols} hvroutes={has_hv}")
    print(f"bitstream : {os.path.relpath(bin_path)}")
    print(f"io_map    : {os.path.relpath(iomap_path)}  "
          f"(copy it next to the header)")
    print(f"header    : {args.output} (array {array_name}[CONFIG_SIZE])")
    print("round-trip: OK (re-emitted bitstream is byte-identical)")


if __name__ == "__main__":
    main()
