// Generated by map2bitstream.py from fir mapped on configs/4x4-HV.hjson
// Replayed from the committed regress/4x4-HV/fir/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input0   ch 13  router 2 ver_ise  address=0x200 stride=4 size=100
//   out  output0  ch 8   south of PE12     address=0x400 size=100

#include <stdint.h>
#include "strela.h"

#define FIR_KERNEL_IN_INPUT0_CH 13
#define FIR_KERNEL_OUT_OUTPUT0_CH 8

uint32_t fir_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00008002, 0x021C0300, 0x00000204, 0x00000000, 0xFFFFFFF8, // 12
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 8
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 4
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 0
    0x00000000, // routernode0

    0x00004203, 0x008C1800, 0x00000100, 0x00000000, 0x00000000, // 13
    0x00004203, 0x008C0300, 0x00004200, 0x00000000, 0x00000000, // 9
    0x00008103, 0x001C0300, 0x00004200, 0x00000000, 0x00000000, // 5
    0x00000802, 0x00000100, 0x00000000, 0x00000000, 0x00000000, // 1
    0x00000000, // routernode1

    0x10000000, 0x026C1800, 0x00000102, 0x00000000, 0x00000020, // 14
    0x10000000, 0x026C1800, 0x00000102, 0x00000000, 0x00000060, // 10
    0x10000000, 0x026C1800, 0x00000102, 0x00000000, 0x00000060, // 6
    0x10000000, 0x026C1800, 0x00004102, 0x00000000, 0x00000020, // 2
    0x000000F8, // routernode2

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 15
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 11
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 7
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 3
    0x00000000 // routernode3
};
