// Generated by map2bitstream.py from find2min mapped on configs/4x4-HV.hjson
// Replayed from the committed regress/4x4-HV/find2min/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input0   ch 9   router 0 ver_ise  address=0x200 stride=4 size=100
//   out  output0  ch 8   south of PE12     address=0x400 size=1
//   out  output2  ch 11  router 1 ver_ose  address=0x408 size=1
//   out  output1  ch 13  router 2 ver_ose  address=0x404 size=1
//   out  output3  ch 15  router 3 ver_ose  address=0x40C size=1

#include <stdint.h>
#include "strela.h"

#define FIND2MIN_KERNEL_IN_INPUT0_CH 9
#define FIND2MIN_KERNEL_OUT_OUTPUT0_CH 8
#define FIND2MIN_KERNEL_OUT_OUTPUT2_CH 11
#define FIND2MIN_KERNEL_OUT_OUTPUT1_CH 13
#define FIND2MIN_KERNEL_OUT_OUTPUT3_CH 15

uint32_t find2min_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x20000081, 0x235C040C, 0x00655A20, 0x000000FF, 0x00000000, // 12
    0x101400A5, 0x216C0004, 0x00000060, 0x00000000, 0x00000000, // 8
    0x20200004, 0x032C0300, 0x00000259, 0x00000000, 0x00000000, // 4
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 0
    0x000000E8, // routernode0

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 13
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 9
    0x00004002, 0x34DC4062, 0x006554A0, 0x00000000, 0x00000000, // 5
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 1
    0x0001930A, // routernode1

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 14
    0x00002002, 0x27DC4061, 0x006554A0, 0x000000FF, 0x00000000, // 10
    0x04000219, 0x358C0062, 0x00000420, 0x00000000, 0x00000000, // 6
    0x00000000, 0xC0440300, 0x00004200, 0x00000000, 0x00000001, // 2
    0x0003130B, // routernode2

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 15
    0x08000008, 0x03BC180D, 0x00000919, 0x00000000, 0x00000000, // 11
    0x0408000C, 0x29DC4000, 0x006550A0, 0x00000000, 0x00000000, // 7
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 3
    0x0000010A // routernode3
};
