// Generated by map2bitstream.py from fw_hv mapped on configs/4x4-HV.hjson
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input1   ch 0   west of PE12      address=0x204 stride=4 size=100
//   in   input2   ch 2   west of PE8       address=0x208 stride=4 size=100
//   in   input10  ch 4   west of PE4       address=0x2c4 stride=4 size=100
//   in   input11  ch 6   west of PE0       address=0x2c8 stride=4 size=100
//   in   input9   ch 8   north of PE0      address=0x2c0 stride=4 size=100
//   in   input0   ch 11  router 1 ver_ise  address=0x200 stride=4 size=100
//   in   input6   ch 13  router 2 ver_ise  address=0x280 stride=4 size=100
//   in   input3   ch 14  north of PE3      address=0x240 stride=4 size=100
//   in   input5   ch 16  east of PE3       address=0x248 stride=4 size=100
//   in   input4   ch 18  east of PE7       address=0x244 stride=4 size=100
//   in   input8   ch 20  east of PE11      address=0x288 stride=4 size=100
//   in   input7   ch 22  east of PE15      address=0x284 stride=4 size=100
//   out  output3  ch 9   router 0 ver_ose  address=0x50c size=100
//   out  output0  ch 10  south of PE13     address=0x500 size=100
//   out  output2  ch 12  south of PE14     address=0x508 size=100
//   out  output1  ch 15  router 3 ver_ose  address=0x504 size=100

#include <stdint.h>
#include "strela.h"

#define FW_HV_KERNEL_IN_INPUT1_CH 0
#define FW_HV_KERNEL_IN_INPUT2_CH 2
#define FW_HV_KERNEL_IN_INPUT10_CH 4
#define FW_HV_KERNEL_IN_INPUT11_CH 6
#define FW_HV_KERNEL_IN_INPUT9_CH 8
#define FW_HV_KERNEL_IN_INPUT0_CH 11
#define FW_HV_KERNEL_IN_INPUT6_CH 13
#define FW_HV_KERNEL_IN_INPUT3_CH 14
#define FW_HV_KERNEL_IN_INPUT5_CH 16
#define FW_HV_KERNEL_IN_INPUT4_CH 18
#define FW_HV_KERNEL_IN_INPUT8_CH 20
#define FW_HV_KERNEL_IN_INPUT7_CH 22
#define FW_HV_KERNEL_OUT_OUTPUT3_CH 9
#define FW_HV_KERNEL_OUT_OUTPUT0_CH 10
#define FW_HV_KERNEL_OUT_OUTPUT2_CH 12
#define FW_HV_KERNEL_OUT_OUTPUT1_CH 15

uint32_t fw_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x08000109, 0x003C0060, 0x00000400, 0x00000000, 0x00000000, // 12
    0x0040800A, 0x021C0260, 0x00000418, 0x00000000, 0x00000000, // 8
    0x08000109, 0x003C006C, 0x00000C00, 0x00000000, 0x00000000, // 4
    0x0050224F, 0x250C0200, 0x000000A0, 0x00000000, 0x00000000, // 0
    0x00000109, // routernode0

    0x15000089, 0x21EC0308, 0x00000220, 0x00000000, 0x00000000, // 13
    0x1050000C, 0x016C1A00, 0x00000101, 0x00000000, 0x00000000, // 9
    0x04000209, 0x018C000C, 0x00000801, 0x00000000, 0x00000000, // 5
    0x0060000C, 0x022C1A00, 0x00000118, 0x00000000, 0x00000000, // 1
    0x000000C8, // routernode1

    0x10005083, 0x20EC0300, 0x00000220, 0x00000000, 0x00000000, // 14
    0x10100806, 0x016C0160, 0x00000401, 0x00000000, 0x00000000, // 10
    0x00004203, 0x008C000C, 0x00000801, 0x00000000, 0x00000000, // 6
    0x00200806, 0x022C0160, 0x00000418, 0x00000000, 0x00000000, // 2
    0x000000C8, // routernode2

    0x00008103, 0x001C1800, 0x00000100, 0x00000000, 0x00000000, // 15
    0x0800080A, 0x023C1900, 0x00000118, 0x00000000, 0x00000000, // 11
    0x00008103, 0x001C180C, 0x00000900, 0x00000000, 0x00000000, // 7
    0x02100A1F, 0x2D0C0100, 0x000000A0, 0x00000000, 0x00000000, // 3
    0x00000109 // routernode3
};
