// Generated by map2bitstream.py from fw_hv mapped on configs/4x4-HV.hjson
// Replayed from the committed regress/4x4-HV/fw_hv/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input0   ch 0   west of PE12       address=0x200 stride=4 size=100
//   in   input2   ch 2   west of PE8        address=0x208 stride=4 size=100
//   in   input1   ch 4   west of PE4        address=0x204 stride=4 size=100
//   in   input4   ch 6   west of PE0        address=0x244 stride=4 size=100
//   in   input5   ch 8   north of PE0       address=0x248 stride=4 size=100
//   in   input3   ch 10  north of PE1       address=0x240 stride=4 size=100
//   in   input9   ch 13  router 2 ver_ise   address=0x2c0 stride=4 size=100
//   in   input7   ch 14  north of PE3       address=0x284 stride=4 size=100
//   in   input8   ch 16  east of PE3        address=0x288 stride=4 size=100
//   in   input6   ch 19  router 1 hor_east  address=0x280 stride=4 size=100
//   in   input10  ch 20  east of PE11       address=0x2c4 stride=4 size=100
//   in   input11  ch 22  east of PE15       address=0x2c8 stride=4 size=100
//   out  output0  ch 8   south of PE12      address=0x500 size=100
//   out  output1  ch 11  router 1 ver_ose   address=0x504 size=100
//   out  output3  ch 12  south of PE14      address=0x50c size=100
//   out  output2  ch 15  router 3 ver_ose   address=0x508 size=100

#include <stdint.h>
#include "strela.h"

#define FW_KERNEL_IN_INPUT0_CH 0
#define FW_KERNEL_IN_INPUT2_CH 2
#define FW_KERNEL_IN_INPUT1_CH 4
#define FW_KERNEL_IN_INPUT4_CH 6
#define FW_KERNEL_IN_INPUT5_CH 8
#define FW_KERNEL_IN_INPUT3_CH 10
#define FW_KERNEL_IN_INPUT9_CH 13
#define FW_KERNEL_IN_INPUT7_CH 14
#define FW_KERNEL_IN_INPUT8_CH 16
#define FW_KERNEL_IN_INPUT6_CH 19
#define FW_KERNEL_IN_INPUT10_CH 20
#define FW_KERNEL_IN_INPUT11_CH 22
#define FW_KERNEL_OUT_OUTPUT0_CH 8
#define FW_KERNEL_OUT_OUTPUT1_CH 11
#define FW_KERNEL_OUT_OUTPUT3_CH 12
#define FW_KERNEL_OUT_OUTPUT2_CH 15

uint32_t fw_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x0900210B, 0x243C0308, 0x00000220, 0x00000000, 0x00000000, // 12
    0x0120012D, 0x002C0068, 0x00000401, 0x00000000, 0x00000000, // 8
    0x0810004D, 0x013C0300, 0x00000200, 0x00000000, 0x00000000, // 4
    0x08000109, 0x003C0360, 0x00000600, 0x00000000, 0x00000000, // 0
    0x00000000, // routernode0

    0x00000201, 0x020C1800, 0x00000118, 0x00000000, 0x00000000, // 13
    0x00400209, 0x020C020C, 0x00000818, 0x00000000, 0x00000000, // 9
    0x0404020D, 0x018C0304, 0x00000201, 0x00000000, 0x00000000, // 5
    0x0408022D, 0x298C0000, 0x000000A0, 0x00000000, 0x00000000, // 1
    0x00031B09, // routernode1

    0x10002103, 0x246C0300, 0x00000220, 0x00000000, 0x00000000, // 14
    0x10004802, 0x00EC0160, 0x00000401, 0x00000000, 0x00000000, // 10
    0x80004043, 0x00FC000C, 0x00000801, 0x00000000, 0x00000000, // 6
    0x00200004, 0x022C0300, 0x00000218, 0x00000000, 0x00000000, // 2
    0x000000C8, // routernode2

    0x00001203, 0x020C1800, 0x00000118, 0x00000000, 0x00000000, // 15
    0x0050800E, 0x011C1A00, 0x00000100, 0x00000000, 0x00000000, // 11
    0x82000119, 0x2C7C0000, 0x000000A0, 0x00000000, 0x00000000, // 7
    0x00004203, 0x008C0300, 0x00000200, 0x00000000, 0x00000000, // 3
    0x0000010A // routernode3
};
