// Generated by map2bitstream.py from dither_filter mapped on configs/4x4-HV.hjson
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input0   ch 14  north of PE3   address=0x200 stride=4 size=100
//   out  output0  ch 10  south of PE13  address=0x400 size=100

#include <stdint.h>
#include "strela.h"

#define DITHER_FILTER_KERNEL_IN_INPUT0_CH 14
#define DITHER_FILTER_KERNEL_OUT_OUTPUT0_CH 10

uint32_t dither_filter_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 12
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 8
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 4
    0x00008002, 0x021C0060, 0x00000401, 0x00000000, 0x000000FF, // 0
    0x00000000, // routernode0

    0x10000000, 0x026C0300, 0x00000202, 0x00000000, 0x000000FF, // 13
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 9
    0x00000201, 0x020C0000, 0x00000098, 0x00000000, 0xFFFFFF81, // 5
    0x44008C0A, 0x319C0960, 0x00004420, 0x00000000, 0x00000000, // 1
    0x0000009A, // routernode1

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 14
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 10
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 6
    0x0400800A, 0x019C1800, 0x00000100, 0x00000000, 0x00000000, // 2
    0x00000000, // routernode2

    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 15
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 11
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 7
    0x00000201, 0x020C1800, 0x00000105, 0x00000000, 0x000000FF, // 3
    0x00000000 // routernode3
};
