// Generated by map2bitstream.py from relu_opt mapped on configs/4x4-HV.hjson
// Replayed from the committed regress/4x4-HV/relu_opt/bitstream.bin by regress2kernel.py (no mapper run)
// Fabric: 4x4 with HV routers
//
// I/O bindings (the channel index is the streaming-engine index):
//   in   input0   ch 9   router 0 ver_ise  address=0x200 stride=4 size=100
//   in   input2   ch 11  router 1 ver_ise  address=0x400 stride=4 size=100
//   in   input1   ch 13  router 2 ver_ise  address=0x300 stride=4 size=100
//   in   input3   ch 15  router 3 ver_ise  address=0x500 stride=4 size=100
//   out  output0  ch 8   south of PE12     address=0x600 size=100
//   out  output2  ch 10  south of PE13     address=0x800 size=100
//   out  output1  ch 12  south of PE14     address=0x700 size=100
//   out  output3  ch 14  south of PE15     address=0x900 size=100

#include <stdint.h>
#include "strela.h"

#define RELU_OPT_KERNEL_IN_INPUT0_CH 9
#define RELU_OPT_KERNEL_IN_INPUT2_CH 11
#define RELU_OPT_KERNEL_IN_INPUT1_CH 13
#define RELU_OPT_KERNEL_IN_INPUT3_CH 15
#define RELU_OPT_KERNEL_OUT_OUTPUT0_CH 8
#define RELU_OPT_KERNEL_OUT_OUTPUT2_CH 10
#define RELU_OPT_KERNEL_OUT_OUTPUT1_CH 12
#define RELU_OPT_KERNEL_OUT_OUTPUT3_CH 14

uint32_t relu_opt_kernel[CONFIG_SIZE] __attribute__((section(".xheep_data_interleaved"))) = {
    0x20000081, 0x234C0300, 0x00000220, 0x00000000, 0x00000000, // 12
    0x10000000, 0x026C0300, 0x00000218, 0x00000000, 0x00000000, // 8
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 4
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 0
    0x000000C8, // routernode0

    0x20000081, 0x234C0300, 0x00000220, 0x00000000, 0x00000000, // 13
    0x10000000, 0x026C0300, 0x00000218, 0x00000000, 0x00000000, // 9
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 5
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 1
    0x000000C8, // routernode1

    0x20000081, 0x234C0300, 0x00000220, 0x00000000, 0x00000000, // 14
    0x10000000, 0x026C0300, 0x00000218, 0x00000000, 0x00000000, // 10
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 6
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 2
    0x000000C8, // routernode2

    0x20000081, 0x234C0300, 0x00000220, 0x00000000, 0x00000000, // 15
    0x10000000, 0x026C0300, 0x00000218, 0x00000000, 0x00000000, // 11
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 7
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, // 3
    0x000000C8 // routernode3
};
